### ISSUE TITLE
How to enter a dev shell?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [shymega/esp32-dev.nix#1]
I am used to dev shells with `flake.nix`, but it seems like there are no files for doing `nix develop`. What is the command to enter a devShell or create a flake that uses these packages for a dev shell? I tried going in the `shells` folder and running
```
nix-shell esp32s2-idf-rust.nix
error:
       … while calling the 'import' builtin
         at /home/rajas/Documents/esp32-dev.nix/shells/esp32s2-idf-rust.nix:1:10:
            1| { pkgs ? import ../default.nix }:
             |          ^
            2| pkgs.mkShell {

       error: path '/home/rajas/Documents/esp32-dev.nix/default.nix' does not exist
```

**Comment by shymega** [comment]
This project is a prototype. It is not ready for everyday use. I will close this issue for now, as it's a WIP, and an expected bug.
